INSERT INTO groceries (dashboard_id, text, done) VALUES
(1, 'Bread', false),
(1, 'Yogurt', false),
(1, 'Wheat Wraps', false),
(1, 'Suraj Naan', false),
(1, 'Kraft Cheese', false),
(1, 'Turkey Breast', false),
(1, 'Bear Paws', false),
(1, 'Grade A Eggs', true),
(1, 'Lettuce', true),
(1, 'Vanilla Icecream', true),
(1, 'Old Dutch BBQ', true),
(1, 'Apple Juice', true),
(1, 'Hamburger Buns', true),
(4, 'Bread', false),
(4, 'Yogurt', false),
(4, 'Wheat Wraps', false),
(4, 'Suraj Naan', false),
(4, 'Kraft Cheese', false),
(4, 'Turkey Breast', false),
(4, 'Bear Paws', false),
(4, 'Grade A Eggs', true),
(4, 'Lettuce', true),
(4, 'Vanilla Icecream', true),
(4, 'Old Dutch BBQ', true),
(4, 'Apple Juice', true),
(4, 'Hamburger Buns', true),
(7, 'Bread', false),
(7, 'Yogurt', false),
(7, 'Wheat Wraps', false),
(7, 'Suraj Naan', false),
(7, 'Kraft Cheese', false),
(7, 'Turkey Breast', false),
(7, 'Bear Paws', false),
(7, 'Grade A Eggs', true),
(7, 'Lettuce', true),
(7, 'Vanilla Icecream', true),
(7, 'Old Dutch BBQ', true),
(7, 'Apple Juice', true),
(7, 'Hamburger Buns', true),
(10, 'Bread', false),
(10, 'Yogurt', false),
(10, 'Wheat Wraps', false),
(10, 'Suraj Naan', false),
(10, 'Kraft Cheese', false),
(10, 'Turkey Breast', false),
(10, 'Bear Paws', false),
(10, 'Grade A Eggs', true),
(10, 'Lettuce', true),
(10, 'Vanilla Icecream', true),
(10, 'Old Dutch BBQ', true),
(10, 'Apple Juice', true),
(10, 'Hamburger Buns', true);