INSERT INTO ingredients (recipe_id, item, measurement) VALUES
(1, 'Lean Ground Beed', '3/4 pound'),
(1, 'Minced Onions', '1/2 cup'),
(1, 'Garlic', '2 cloves'),
(1, 'Tomato Paste', '2 cans'),
(1, 'Italian Seasoning', '1 teaspoon'),
(1, 'Lasagna Noodles', '12 pcs'),
(1, 'Cheese', '3/4 pound'),
(2, 'Lean Ground Beed', '3/4 pound'),
(2, 'Minced Onions', '1/2 cup'),
(2, 'Garlic', '2 cloves'),
(2, 'Tomato Paste', '2 cans'),
(2, 'Italian Seasoning', '1 teaspoon'),
(2, 'Lasagna Noodles', '12 pcs'),
(2, 'Cheese', '3/4 pound'),
(3, 'Lean Ground Beed', '3/4 pound'),
(3, 'Minced Onions', '1/2 cup'),
(3, 'Garlic', '2 cloves'),
(3, 'Tomato Paste', '2 cans'),
(3, 'Italian Seasoning', '1 teaspoon'),
(3, 'Lasagna Noodles', '12 pcs'),
(3, 'Cheese', '3/4 pound'),
(4, 'Lean Ground Beed', '3/4 pound'),
(4, 'Minced Onions', '1/2 cup'),
(4, 'Garlic', '2 cloves'),
(4, 'Tomato Paste', '2 cans'),
(4, 'Italian Seasoning', '1 teaspoon'),
(4, 'Lasagna Noodles', '12 pcs'),
(4, 'Cheese', '3/4 pound'),
(5, 'Lean Ground Beed', '3/4 pound'),
(5, 'Minced Onions', '1/2 cup'),
(5, 'Garlic', '2 cloves'),
(5, 'Tomato Paste', '2 cans'),
(5, 'Italian Seasoning', '1 teaspoon'),
(5, 'Lasagna Noodles', '12 pcs'),
(5, 'Cheese', '3/4 pound'),
(6, 'Lean Ground Beed', '3/4 pound'),
(6, 'Minced Onions', '1/2 cup'),
(6, 'Garlic', '2 cloves'),
(6, 'Tomato Paste', '2 cans'),
(6, 'Italian Seasoning', '1 teaspoon'),
(6, 'Lasagna Noodles', '12 pcs'),
(6, 'Cheese', '3/4 pound'),
(7, 'Lean Ground Beed', '3/4 pound'),
(7, 'Minced Onions', '1/2 cup'),
(7, 'Garlic', '2 cloves'),
(7, 'Tomato Paste', '2 cans'),
(7, 'Italian Seasoning', '1 teaspoon'),
(7, 'Lasagna Noodles', '12 pcs'),
(7, 'Cheese', '3/4 pound'),
(8, 'Lean Ground Beed', '3/4 pound'),
(8, 'Minced Onions', '1/2 cup'),
(8, 'Garlic', '2 cloves'),
(8, 'Tomato Paste', '2 cans'),
(8, 'Italian Seasoning', '1 teaspoon'),
(8, 'Lasagna Noodles', '12 pcs'),
(8, 'Cheese', '3/4 pound'),
(9, 'Lean Ground Beed', '3/4 pound'),
(9, 'Minced Onions', '1/2 cup'),
(9, 'Garlic', '2 cloves'),
(9, 'Tomato Paste', '2 cans'),
(9, 'Italian Seasoning', '1 teaspoon'),
(9, 'Lasagna Noodles', '12 pcs'),
(9, 'Cheese', '3/4 pound'),
(10, 'Lean Ground Beed', '3/4 pound'),
(10, 'Minced Onions', '1/2 cup'),
(10, 'Garlic', '2 cloves'),
(10, 'Tomato Paste', '2 cans'),
(10, 'Italian Seasoning', '1 teaspoon'),
(10, 'Lasagna Noodles', '12 pcs'),
(10, 'Cheese', '3/4 pound'),
(11, 'Lean Ground Beed', '3/4 pound'),
(11, 'Minced Onions', '1/2 cup'),
(11, 'Garlic', '2 cloves'),
(11, 'Tomato Paste', '2 cans'),
(11, 'Italian Seasoning', '1 teaspoon'),
(11, 'Lasagna Noodles', '12 pcs'),
(11, 'Cheese', '3/4 pound'),
(12, 'Lean Ground Beed', '3/4 pound'),
(12, 'Minced Onions', '1/2 cup'),
(12, 'Garlic', '2 cloves'),
(12, 'Tomato Paste', '2 cans'),
(12, 'Italian Seasoning', '1 teaspoon'),
(12, 'Lasagna Noodles', '12 pcs'),
(12, 'Cheese', '3/4 pound'),
(13, 'Lean Ground Beed', '3/4 pound'),
(13, 'Minced Onions', '1/2 cup'),
(13, 'Garlic', '2 cloves'),
(13, 'Tomato Paste', '2 cans'),
(13, 'Italian Seasoning', '1 teaspoon'),
(13, 'Lasagna Noodles', '12 pcs'),
(13, 'Cheese', '3/4 pound'),
(14, 'Lean Ground Beed', '3/4 pound'),
(14, 'Minced Onions', '1/2 cup'),
(14, 'Garlic', '2 cloves'),
(14, 'Tomato Paste', '2 cans'),
(14, 'Italian Seasoning', '1 teaspoon'),
(14, 'Lasagna Noodles', '12 pcs'),
(14, 'Cheese', '3/4 pound'),
(15, 'Lean Ground Beed', '3/4 pound'),
(15, 'Minced Onions', '1/2 cup'),
(15, 'Garlic', '2 cloves'),
(15, 'Tomato Paste', '2 cans'),
(15, 'Italian Seasoning', '1 teaspoon'),
(15, 'Lasagna Noodles', '12 pcs'),
(15, 'Cheese', '3/4 pound'),
(16, 'Lean Ground Beed', '3/4 pound'),
(16, 'Minced Onions', '1/2 cup'),
(16, 'Garlic', '2 cloves'),
(16, 'Tomato Paste', '2 cans'),
(16, 'Italian Seasoning', '1 teaspoon'),
(16, 'Lasagna Noodles', '12 pcs'),
(16, 'Cheese', '3/4 pound'),
(17, 'Lean Ground Beed', '3/4 pound'),
(17, 'Minced Onions', '1/2 cup'),
(17, 'Garlic', '2 cloves'),
(17, 'Tomato Paste', '2 cans'),
(17, 'Italian Seasoning', '1 teaspoon'),
(17, 'Lasagna Noodles', '12 pcs'),
(17, 'Cheese', '3/4 pound'),
(18, 'Lean Ground Beed', '3/4 pound'),
(18, 'Minced Onions', '1/2 cup'),
(18, 'Garlic', '2 cloves'),
(18, 'Tomato Paste', '2 cans'),
(18, 'Italian Seasoning', '1 teaspoon'),
(18, 'Lasagna Noodles', '12 pcs'),
(18, 'Cheese', '3/4 pound'),
(19, 'Lean Ground Beed', '3/4 pound'),
(19, 'Minced Onions', '1/2 cup'),
(19, 'Garlic', '2 cloves'),
(19, 'Tomato Paste', '2 cans'),
(19, 'Italian Seasoning', '1 teaspoon'),
(19, 'Lasagna Noodles', '12 pcs'),
(19, 'Cheese', '3/4 pound'),
(20, 'Lean Ground Beed', '3/4 pound'),
(20, 'Minced Onions', '1/2 cup'),
(20, 'Garlic', '2 cloves'),
(20, 'Tomato Paste', '2 cans'),
(20, 'Italian Seasoning', '1 teaspoon'),
(20, 'Lasagna Noodles', '12 pcs'),
(20, 'Cheese', '3/4 pound'),
(21, 'Lean Ground Beed', '3/4 pound'),
(21, 'Minced Onions', '1/2 cup'),
(21, 'Garlic', '2 cloves'),
(21, 'Tomato Paste', '2 cans'),
(21, 'Italian Seasoning', '1 teaspoon'),
(21, 'Lasagna Noodles', '12 pcs'),
(21, 'Cheese', '3/4 pound'),
(22, 'Lean Ground Beed', '3/4 pound'),
(22, 'Minced Onions', '1/2 cup'),
(22, 'Garlic', '2 cloves'),
(22, 'Tomato Paste', '2 cans'),
(22, 'Italian Seasoning', '1 teaspoon'),
(22, 'Lasagna Noodles', '12 pcs'),
(22, 'Cheese', '3/4 pound'),
(23, 'Lean Ground Beed', '3/4 pound'),
(23, 'Minced Onions', '1/2 cup'),
(23, 'Garlic', '2 cloves'),
(23, 'Tomato Paste', '2 cans'),
(23, 'Italian Seasoning', '1 teaspoon'),
(23, 'Lasagna Noodles', '12 pcs'),
(23, 'Cheese', '3/4 pound'),
(24, 'Lean Ground Beed', '3/4 pound'),
(24, 'Minced Onions', '1/2 cup'),
(24, 'Garlic', '2 cloves'),
(24, 'Tomato Paste', '2 cans'),
(24, 'Italian Seasoning', '1 teaspoon'),
(24, 'Lasagna Noodles', '12 pcs'),
(24, 'Cheese', '3/4 pound'),
(25, 'Lean Ground Beed', '3/4 pound'),
(25, 'Minced Onions', '1/2 cup'),
(25, 'Garlic', '2 cloves'),
(25, 'Tomato Paste', '2 cans'),
(25, 'Italian Seasoning', '1 teaspoon'),
(25, 'Lasagna Noodles', '12 pcs'),
(25, 'Cheese', '3/4 pound'),
(26, 'Lean Ground Beed', '3/4 pound'),
(26, 'Minced Onions', '1/2 cup'),
(26, 'Garlic', '2 cloves'),
(26, 'Tomato Paste', '2 cans'),
(26, 'Italian Seasoning', '1 teaspoon'),
(26, 'Lasagna Noodles', '12 pcs'),
(26, 'Cheese', '3/4 pound'),
(27, 'Lean Ground Beed', '3/4 pound'),
(27, 'Minced Onions', '1/2 cup'),
(27, 'Garlic', '2 cloves'),
(27, 'Tomato Paste', '2 cans'),
(27, 'Italian Seasoning', '1 teaspoon'),
(27, 'Lasagna Noodles', '12 pcs'),
(27, 'Cheese', '3/4 pound'),
(28, 'Lean Ground Beed', '3/4 pound'),
(28, 'Minced Onions', '1/2 cup'),
(28, 'Garlic', '2 cloves'),
(28, 'Tomato Paste', '2 cans'),
(28, 'Italian Seasoning', '1 teaspoon'),
(28, 'Lasagna Noodles', '12 pcs'),
(28, 'Cheese', '3/4 pound');
