INSERT INTO chores (dashboard_id, text) VALUES
(1, 'put away clean dishes', 'Sam'),
(1, 'vacuum upper floor', 'Sam'),
(1, 'scrub toilets'),
(1, 'empty dishwasher'),
(1, 'eat your wheaties'),
(2, 'put away clean dishes'),
(2, 'vacuum upper floor'),
(2, 'scrub toilets'),
(2, 'empty dishwasher'),
(2, 'eat your wheaties'),
(3, 'put away clean dishes'),
(3, 'vacuum upper floor'),
(3, 'scrub toilets'),
(3, 'empty dishwasher'),
(3, 'eat your wheaties');