INSERT INTO chores (dashboard_id, text, name, done) VALUES
(1, 'Complete final project', default, default),
(1, 'Deploy final project', default, default),
(1, 'Prep weekly meals', default, true),
(1, 'Vacuum the floors', default, true),
(4, 'Complete final project', default, default),
(4, 'Deploy final project', default, default),
(4, 'Prep weekly meals', default, true),
(4, 'Vacuum the floors', default, true),
(7, 'Complete final project', default, default),
(7, 'Deploy final project', default, default),
(7, 'Prep weekly meals', default, true),
(7, 'Vacuum the floors', default, true),
(10, 'Complete final project', default, default),
(10, 'Deploy final project', default, default),
(10, 'Prep weekly meals', default, true),
(10, 'Vacuum the floors', default, true);