DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS dashboards CASCADE;
DROP TABLE IF EXISTS groceries CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS chores CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE dashboards (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  groceries BOOLEAN NOT NULL,
  recipes BOOLEAN NOT NULL,
  events BOOLEAN NOT NULL,
  polls BOOLEAN NOT NULL,
  photos BOOLEAN NOT NULL,
  chores BOOLEAN NOT NULL,
  contacts BOOLEAN NOT NULL
);

CREATE TABLE links (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  admin BOOLEAN NOT NULL
);

CREATE TABLE groceries (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  done BOOLEAN DEFAULT FALSE
);

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  directions TEXT NOT NULL
);

CREATE TABLE ingredients (
  id SERIAL PRIMARY KEY NOT NULL,
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE,
  item VARCHAR(255) NOT NULL,
  measurement VARCHAR(255) NOT NULL
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  start_at DATE NOT NULL,
  end_at DATE NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  choice VARCHAR(255) NOT NULL,
  votes INTEGER
);

CREATE TABLE photos (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  img_url VARCHAR(255) NOT NULL,
  text VARCHAR(255) NOT NULL
);

CREATE TABLE chores (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  done BOOLEAN,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE contacts (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);