DROP TABLE IF EXISTS groceries CASCADE;

CREATE TABLE groceries (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  done BOOLEAN DEFAULT FALSE
);
