DROP TABLE IF EXISTS chores CASCADE;

CREATE TABLE chores (
  id SERIAL PRIMARY KEY NOT NULL,
  dashboard_id INTEGER REFERENCES dashboards(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  done BOOLEAN,
  name VARCHAR(255) NOT NULL
);
